articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),
]

modelForm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

articles/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'
        

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm

def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles, 
    }
    return render(request, 'index.html', context)

def create(request):
    # 모든 경우의 수
    # 1. GET: form을 만들어서 html 문서를 사용자에게 리턴(1~4)
    # 2. POST: invalid data(데이터 검증에 실패하는 경우) (5~9)
    # -> 검증에 성공한 데이터만 가지고 form을 만들어서 html 문서를 사용자에게 리턴
    # 3. POST valid data(데이터 검증에 성공하는 경우)
    # -> DB에 데이터 저장 후 index 페이지로 redirect
    
    # 5. POST요청 (데이터가 잘못들어온경우)
    # 10. POST요청 (데이터가 잘 들어온경우)
    if request.method == 'POST':
        # 6. 사용자가 입력한 정보(x)를 담아서 form을 생성
        # 11. 사용자가 입력한 정보(o)를 담아서 form을 생성
        form = ArticleForm(request.POST)
        # 7. form을 검증(실패)
        # 12. form을 검증(성공)
        if form.is_valid():
            # 13. form을 article에 저장
            article = form.save()
            # 14. index페이지로 redirect
            return redirect('articles:index')
    # 1. GET요청
    else:
        # 2. 비어있는 form을 만들어서
        form = ArticleForm()
    # 3. context dict에 담고
    # 8. 검증에 실패한 form을 context dict에 담고
    context = {
        'form': form,
    }
    # 4. form.html을 랜더링
    # 9. form.html을 랜더링
    return render(request, 'form.html', context)

def delete(request, id):
    article = Article.objects.get(id=id)
    article.delete()
    return redirect('articles:index')

def update(request, id):
    article = Article.objects.get(id=id)
    if request.method =='POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = ArticleForm(instance=article)  
    context = {
        'form': form,
    }
    return render(request, 'form.html', context) 

articles/templates/form.html
{% extends 'base.html' %}

{% block body %}
    {% if request.resolver_match.url_name == 'update' %}
        <h1>게시물 수정</h1>
    {% else %}
        <h1>게시물 생성</h1>
    {% endif %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <h1>index입니다.</h1>
    {% for article in articles %}
        <p>{{ article.title }}</p>
        <p>{{ article.content }}</p>
        <p>{{ article.updated_at}}</p>
        <a href="{% url 'articles:delete' id=article.id %}">delete</a>
        <a href="{% url 'articles:update' id=article.id %}">update</a>
        <hr>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'articles:index' %}">Home</a>
    <a href="{% url 'articles:create' %}">Create</a>
    {% block body %}
    {% endblock %}   
</body>
</html>